### ISSUE TITLE
How to Build Binary for nexys4ddr Board?

### ISSUE THREAD

**Issue by yunchenlo** [syntacore/scr1-sdk#1]
Hello,

In the sw folder, there is no makefile for compiling bin for nexys4ddr board.

Could you please update the makefile or is there any other ways?

Thank you very much!
Yun-Chen Lo

**Comment by dp-sc** [comment]
Hello,

We added plf.mk for nexys4ddr support: 

commit: 81c86244dcae33d2ceaf5115b3d1a106456da579

Please, check it.

Dmitri

**Comment by yunchenlo** [comment]
ok thanks
