### ISSUE TITLE
How to build sdk of digilent Pmod SF3?

### ISSUE THREAD

**Issue by ruen1020** [syntacore/scr1-sdk#2]
Hi,
Below is an example of digilent Pmod SF3 and I want to do it on scr1. 

https://github.com/Digilent/vivado-library/tree/master/ip/Pmods/PmodSF3_v1_0/drivers/PmodSF3_v1_0

I have implement dhry by xilinx-sdk and found some difference between your scr1-sdk.
Could you please teach me how to implement the files from xilinx-sdk to scr1-sdk?

**Comment by eb-sc** [comment]
Sorry about the delayed response.

Please, clarify your question:
1) Are you asking for help with the integration of the Digilent's Pmod SF3 hardware IP into the SCR1 SDK's SOC block design?
2) Or you are asking for help with porting of the Pmod SF3 software driver to the SCR1 SDK?

We plan to close this issue in a week if won’t hear from you. In case any follow-up will be needed after that, feel free to re-open or contact us at scr1@syntacore.com


Best regards,
Kate
