### ISSUE TITLE
Debugging support in SCR1

### ISSUE THREAD

**Issue by eppleshine** [syntacore/scr1-sdk#3]
**In sscr1-sdk/docs/nexys4ddr_scr1_guide_en.pdf,** 
**On Page 7**:
If you are going to debug software running on the SCR1 with GDB/OpenOCD, the following
components are also required:
• JTAG Cable Adapter: JTAG-HS2 Programming Cable
https://store.digilentinc.com/jtag-hs2-programming-cable/

**On Page 9**: 
SCR3 JTAG connection on the NEXYS4DDR board is shown in Figure 2.

The SCR1 soc seem to have some kind of debug modules in it. The page 9's statement is confusing me why SCR3 is being said to be having JTAG connection on NEXYS4DDR board? Does SCR1 supports debugging using JTAG-HS2 cable and OpenOCD? If answer to this question is yes, the statement on page 9 needs to be edited.

**Comment by eb-sc** [comment]
Yes, the SCR1 supports debugging. There was a typo in the NEXYS4DDR User Manual.

The document is updated:
https://github.com/syntacore/scr1-sdk/blob/master/docs/nexys4ddr_scr1_guide_en.pdf
