### ISSUE TITLE
Typo in the documentation for de10-lite

### ISSUE THREAD

**Issue by point911** [syntacore/scr1-sdk#4]
doc: de10lite-scr1-guide-en.pdf
chapter: 6.2

instead of: addr: f000200 should be addr: f0000200

**Comment by achuykov-sc** [comment]
Hi @point911, 

It is fixed already in latest documentation. 
![image](https://user-images.githubusercontent.com/106238177/220690657-33768172-5434-4c75-bd3c-932c5c12ff4d.png)

Best regards,
Alexander
