### ISSUE TITLE
can't build de10 project in quartus 21

### ISSUE THREAD

**Issue by point911** [syntacore/scr1-sdk#5]
default sdram ddr ip core mem controller is absent in quartus 21

**Comment by achuykov-sc** [comment]
Hi @point911,

This is Quartus 21+ issue, see here: https://community.intel.com/t5/Programmable-Devices/Where-is-the-SDRAM-controller-IP-in-Quartus-21-Lite/m-p/1370159
As summary: there is no SDRAM controller in Quartus Lite / Free starting from version 21.

Best regards,
Alexander
